## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

matrix:
 allow_failures:
 - julia: nightly

dist: trusty
addons:
  apt:
    packages:
    - xorg-dev
before_script:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

script:
 - julia -e 'using Pkg; pkg"add AbstractPlotting#sd-meshes Makie#master"; Pkg.clone(pwd()); Pkg.build("StatsMakie"); Pkg.test("StatsMakie"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; cd(Pkg.dir("StatsMakie")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg; cd(Pkg.dir("StatsMakie")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
